123
Property index 87 ID is 6898
Property ID: 6898
Starting server on port 8106
Traceback (most recent call last):
  File "/dfs9/dmobley-lab/lilyw7/water-properties-evaluator/02_benchmark/benchmark.py", line 166, in <module>
    main()
  File "/data/homezvol3/lilyw7/miniforge3/envs/evaluator-050/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/homezvol3/lilyw7/miniforge3/envs/evaluator-050/lib/python3.11/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/homezvol3/lilyw7/miniforge3/envs/evaluator-050/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/homezvol3/lilyw7/miniforge3/envs/evaluator-050/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dfs9/dmobley-lab/lilyw7/water-properties-evaluator/02_benchmark/benchmark.py", line 136, in main
    with server:
  File "/data/homezvol3/lilyw7/miniforge3/envs/evaluator-050/lib/python3.11/site-packages/openff/evaluator/server/server.py", line 762, in __enter__
    self.start(asynchronous=True)
  File "/data/homezvol3/lilyw7/miniforge3/envs/evaluator-050/lib/python3.11/site-packages/openff/evaluator/server/server.py", line 727, in start
    self._socket.bind(("localhost", self._port))
OSError: [Errno 98] Address already in use
